name: Print Cybersecurity

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  print-login:
    runs-on: ubuntu-latest

    steps:
    - name: Print Cybersecurity Message
      run: echo "Cybersecurity"
