name: Print Error Handling

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  print-error-handling:
    runs-on: ubuntu-latest

    steps:
    - name: Print Error Handling Message
      run: echo "Error Handling"
